task :converge do
  Dir.chdir("setup") do
    sh("kitchen converge")
  end
end

task :destroy do
  Dir.chdir("setup") do
    sh("kitchen destroy")
  end
end

namespace :upload do
  task :notifications do
    Dir.chdir("notifications") do
      Dir['*.json'].each do |fn|
        sh("knife notification create #{fn}")
      end
    end
  end
  task :rules do
    Dir.chdir("rules") do
      Dir['*.json'].each do |fn|
        sh("knife rule create #{fn}")
      end
    end
  end
end

task :upload do
  sh "chef gem install knife-analytics"
  Rake::Task['upload:notifications'].invoke
  Rake::Task['upload:rules'].invoke
end

task :bootstrap do
  STDOUT.puts "Enter a unique name for your node: "
  name = STDIN.gets.strip
  sh("knife bootstrap -E production -x vagrant -P vagrant --sudo -N #{name} --node-ssl-verify-mode=none 192.168.56.102")
end

namespace :login do
  task :server do
    Dir.chdir("setup") do
      sh "kitchen login default"
    end
  end
  task :analytics do
    Dir.chdir("setup") do
      sh "kitchen login analytics"
    end
  end
  task :client do
    Dir.chdir("setup") do
      sh "kitchen login client"
    end
  end
end
