task :converge do
  Dir.chdir("setup") do
    sh("kitchen converge")
  end
end

task :destroy do
  Dir.chdir("setup") do
    sh("kitchen destroy")
  end
end

namespace :upload do
  task :notifications do
    Dir.chdir("notifications") do
      Dir['*.json'].each do |fn|
        sh("knife notification create #{fn}")
      end
    end
  end
  task :rules do
    Dir.chdir("rules") do
      Dir['*.json'].each do |fn|
        sh("knife rule create #{fn}")
      end
    end
  end
end

task :upload do
  Rake::Task['upload:notifications'].invoke
  Rake::Task['upload:rules'].invoke
end

task :bootstrap do
  STDOUT.puts "Enter a unique name for your node: "
  name = STDIN.gets.strip
  sh("/opt/chefdk/bin/knife bootstrap -E production -x vagrant -P vagrant --sudo -N #{name} --node-ssl-verify-mode=none 192.168.56.102")
end

namespace :login do
  task :server do
    sh "ssh vagrant@192.168.56.100"
  end
  task :analytics do
    sh "ssh vagrant@192.168.56.101"
  end
  task :client do
    sh "ssh vagrant@192.168.56.102"
  end
end
