---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  #- name: centos-6.6
  - name: ubuntu-14.04
    driver:
      network:
        - ["private_network", {ip: "192.168.56.90"}]
        
suites:
  - name: default
    run_list:
      - recipe[chef-cd-workshop::default]
    attributes:
